services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_db
    restart: always
    environment:
      POSTGRES_USER: rag_admin
      POSTGRES_PASSWORD: RAGdustmq12
      POSTGRES_DB: rag_db
    ports:
      - "5433:5432"
    volumes:
      - ./rag_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: rag_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./rag_redisdata:/data